### ISSUE TITLE
Theme doesn't play nice with custom plugin tabs

### ISSUE THREAD

**Issue by svanlaere** [pawedWolf/wolfcms-wint-admintheme#6]
When adding own tabs by using view_page_edit_tabs observer in a plugin
a part of that added tab (or tabs) is usually hidden.

What is a good solution to fix that?

**Comment by SamBrishes** [comment]
Thanks for the bug report.

I found a solution, after an one-hour playtime with the css codes. This solution is currently only tested in Google Chrome and is (maybe) not the best way to fix this problem. I will search (for the next update) for a better way to handle the costum tabs.

### Bugfix
[See develop branch](https://github.com/SamBrishes/wolfcms-wordpress-admintheme/tree/develop)
It concerns only the ```part.content-form.css``` file.

[See all Changes](https://github.com/SamBrishes/wolfcms-wordpress-admintheme/compare/develop#diff-457462b0431705ed86ee97081cf20f28)
I changed the ```position: absolute``` property on the "widgets" into an ```float: right```, removed the ```:before``` pseudo class (which previously served as Widget header) and changed the Behaviour of the part-tabs and part-content container.

### Screenshots
**Costum Tabs**
![quickfix1](https://cloud.githubusercontent.com/assets/10143149/10122956/9496f338-652a-11e5-919b-3ce36722c77d.png)

**More Costum Tabs**
![quickfix2](https://cloud.githubusercontent.com/assets/10143149/10122958/9b96d98c-652a-11e5-818b-4a75a30ac7bd.png)

Sincerely,
Sam.

**Comment by svanlaere** [comment]
Thanks for fixing the issue Sam, in my case it will show the scrollbars since I have a 3 colomn table 
with 2 inputs and a button on each row, so it to wide for that kind of room.
I guess that kind of theming just limits wider tabs.

**Comment by SamBrishes** [comment]
Hmm... Yes, that's true. 
I will look for a better solution to handle this.
